// Catalog of long-acting injectable (LAI) medications used in US mental health
// and substance-use disorder treatment. Sorted alphabetically by brand name.
//
// Sourced from FDA prescribing information and the published clinical reviews
// cited in build notes. Each entry pre-fills the prescribe form with reasonable
// adult starting/maintenance values; the prescriber can still edit any field.
//
// TEST DATA ONLY — alpha build. Not a substitute for current FDA labeling.

export type LaiRoute = "IM" | "SubQ";

export interface LaiCatalogEntry {
  // Display label in the picker — brand and generic together for clarity.
  label: string;
  // Brand name only, used as the Rx `drug` field.
  drug: string;
  // Generic name (informational).
  generic: string;
  // Strength shown on the syringe / vial — fills the Rx `strength` field.
  strength: string;
  // Dosage form — fills the Rx `form` field.
  form: "injection";
  // Route of administration.
  route: LaiRoute;
  // Quantity (typically 1 prefilled syringe / vial).
  quantity: string;
  // Refills allowed before re-evaluation.
  refills: string;
  // Pre-filled sig string the prescriber can accept or override.
  sig: string;
  // Default schedule key used by the LAI routing logic below the form.
  schedule: "q2w" | "monthly" | "q4w" | "q6w" | "q2month" | "q3month" | "q6month" | "asap";
  // Therapeutic category (informational, used to group future filters).
  category:
    | "Antipsychotic (atypical)"
    | "Antipsychotic (typical)"
    | "Opioid use disorder"
    | "Alcohol use disorder";
}

// IMPORTANT: list is sorted alphabetically by `label` at the bottom of this
// file — keep additions in alphabetical order or rely on the sort.
const RAW: LaiCatalogEntry[] = [
  {
    label: "Abilify Asimtufii (aripiprazole) 720 mg",
    drug: "Abilify Asimtufii",
    generic: "aripiprazole",
    strength: "720 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 720 mg intramuscularly every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Abilify Asimtufii (aripiprazole) 960 mg",
    drug: "Abilify Asimtufii",
    generic: "aripiprazole",
    strength: "960 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 960 mg intramuscularly every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Abilify Maintena (aripiprazole) 300 mg",
    drug: "Abilify Maintena",
    generic: "aripiprazole",
    strength: "300 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 300 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Abilify Maintena (aripiprazole) 400 mg",
    drug: "Abilify Maintena",
    generic: "aripiprazole",
    strength: "400 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 400 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Aristada (aripiprazole lauroxil) 441 mg",
    drug: "Aristada",
    generic: "aripiprazole lauroxil",
    strength: "441 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 441 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Aristada (aripiprazole lauroxil) 662 mg",
    drug: "Aristada",
    generic: "aripiprazole lauroxil",
    strength: "662 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 662 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Aristada (aripiprazole lauroxil) 882 mg",
    drug: "Aristada",
    generic: "aripiprazole lauroxil",
    strength: "882 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 882 mg intramuscularly every 42 days (6 weeks)",
    schedule: "q6w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Aristada (aripiprazole lauroxil) 1064 mg",
    drug: "Aristada",
    generic: "aripiprazole lauroxil",
    strength: "1064 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 1064 mg intramuscularly every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Aristada Initio (aripiprazole lauroxil) 675 mg",
    drug: "Aristada Initio",
    generic: "aripiprazole lauroxil",
    strength: "675 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "0",
    sig: "Inject 675 mg intramuscularly once as Aristada initiation dose with 30 mg oral aripiprazole",
    schedule: "asap",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Brixadi (buprenorphine ER) 8 mg weekly",
    drug: "Brixadi",
    generic: "buprenorphine extended-release",
    strength: "8 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 8 mg subcutaneously every 7 days (weekly)",
    schedule: "asap",
    category: "Opioid use disorder",
  },
  {
    label: "Brixadi (buprenorphine ER) 16 mg weekly",
    drug: "Brixadi",
    generic: "buprenorphine extended-release",
    strength: "16 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 16 mg subcutaneously every 7 days (weekly)",
    schedule: "asap",
    category: "Opioid use disorder",
  },
  {
    label: "Brixadi (buprenorphine ER) 64 mg monthly",
    drug: "Brixadi",
    generic: "buprenorphine extended-release",
    strength: "64 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 64 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Opioid use disorder",
  },
  {
    label: "Brixadi (buprenorphine ER) 96 mg monthly",
    drug: "Brixadi",
    generic: "buprenorphine extended-release",
    strength: "96 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 96 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Opioid use disorder",
  },
  {
    label: "Brixadi (buprenorphine ER) 128 mg monthly",
    drug: "Brixadi",
    generic: "buprenorphine extended-release",
    strength: "128 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 128 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Opioid use disorder",
  },
  {
    label: "Fluphenazine decanoate 25 mg/mL",
    drug: "Fluphenazine decanoate",
    generic: "fluphenazine decanoate",
    strength: "25 mg/mL",
    form: "injection",
    route: "IM",
    quantity: "1 mL vial",
    refills: "5",
    sig: "Inject 12.5 mg to 50 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (typical)",
  },
  {
    label: "Haldol Decanoate (haloperidol decanoate) 50 mg/mL",
    drug: "Haldol Decanoate",
    generic: "haloperidol decanoate",
    strength: "50 mg/mL",
    form: "injection",
    route: "IM",
    quantity: "1 mL vial",
    refills: "5",
    sig: "Inject 50 mg to 100 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (typical)",
  },
  {
    label: "Haldol Decanoate (haloperidol decanoate) 100 mg/mL",
    drug: "Haldol Decanoate",
    generic: "haloperidol decanoate",
    strength: "100 mg/mL",
    form: "injection",
    route: "IM",
    quantity: "1 mL vial",
    refills: "5",
    sig: "Inject 100 mg to 200 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (typical)",
  },
  {
    label: "Invega Hafyera (paliperidone palmitate) 1092 mg",
    drug: "Invega Hafyera",
    generic: "paliperidone palmitate",
    strength: "1092 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "1",
    sig: "Inject 1092 mg intramuscularly every 168 days (6 months)",
    schedule: "q6month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Hafyera (paliperidone palmitate) 1560 mg",
    drug: "Invega Hafyera",
    generic: "paliperidone palmitate",
    strength: "1560 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "1",
    sig: "Inject 1560 mg intramuscularly every 168 days (6 months)",
    schedule: "q6month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Sustenna (paliperidone palmitate) 39 mg",
    drug: "Invega Sustenna",
    generic: "paliperidone palmitate",
    strength: "39 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 39 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Sustenna (paliperidone palmitate) 78 mg",
    drug: "Invega Sustenna",
    generic: "paliperidone palmitate",
    strength: "78 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 78 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Sustenna (paliperidone palmitate) 117 mg",
    drug: "Invega Sustenna",
    generic: "paliperidone palmitate",
    strength: "117 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 117 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Sustenna (paliperidone palmitate) 156 mg",
    drug: "Invega Sustenna",
    generic: "paliperidone palmitate",
    strength: "156 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 156 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Sustenna (paliperidone palmitate) 234 mg",
    drug: "Invega Sustenna",
    generic: "paliperidone palmitate",
    strength: "234 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 234 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Trinza (paliperidone palmitate) 273 mg",
    drug: "Invega Trinza",
    generic: "paliperidone palmitate",
    strength: "273 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "3",
    sig: "Inject 273 mg intramuscularly every 84 days (3 months)",
    schedule: "q3month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Trinza (paliperidone palmitate) 410 mg",
    drug: "Invega Trinza",
    generic: "paliperidone palmitate",
    strength: "410 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "3",
    sig: "Inject 410 mg intramuscularly every 84 days (3 months)",
    schedule: "q3month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Trinza (paliperidone palmitate) 546 mg",
    drug: "Invega Trinza",
    generic: "paliperidone palmitate",
    strength: "546 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "3",
    sig: "Inject 546 mg intramuscularly every 84 days (3 months)",
    schedule: "q3month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Invega Trinza (paliperidone palmitate) 819 mg",
    drug: "Invega Trinza",
    generic: "paliperidone palmitate",
    strength: "819 mg",
    form: "injection",
    route: "IM",
    quantity: "1 syringe",
    refills: "3",
    sig: "Inject 819 mg intramuscularly every 84 days (3 months)",
    schedule: "q3month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Perseris (risperidone ER) 90 mg",
    drug: "Perseris",
    generic: "risperidone extended-release",
    strength: "90 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 90 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Perseris (risperidone ER) 120 mg",
    drug: "Perseris",
    generic: "risperidone extended-release",
    strength: "120 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 120 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Risperdal Consta (risperidone) 25 mg",
    drug: "Risperdal Consta",
    generic: "risperidone",
    strength: "25 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 25 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Risperdal Consta (risperidone) 37.5 mg",
    drug: "Risperdal Consta",
    generic: "risperidone",
    strength: "37.5 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 37.5 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Risperdal Consta (risperidone) 50 mg",
    drug: "Risperdal Consta",
    generic: "risperidone",
    strength: "50 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 50 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Rykindo (risperidone) 25 mg",
    drug: "Rykindo",
    generic: "risperidone",
    strength: "25 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 25 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Rykindo (risperidone) 37.5 mg",
    drug: "Rykindo",
    generic: "risperidone",
    strength: "37.5 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 37.5 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Rykindo (risperidone) 50 mg",
    drug: "Rykindo",
    generic: "risperidone",
    strength: "50 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 50 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Sublocade (buprenorphine ER) 100 mg",
    drug: "Sublocade",
    generic: "buprenorphine extended-release",
    strength: "100 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 100 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Opioid use disorder",
  },
  {
    label: "Sublocade (buprenorphine ER) 300 mg",
    drug: "Sublocade",
    generic: "buprenorphine extended-release",
    strength: "300 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 300 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Opioid use disorder",
  },
  {
    label: "Uzedy (risperidone ER) 50 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "50 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 50 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Uzedy (risperidone ER) 75 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "75 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 75 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Uzedy (risperidone ER) 100 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "100 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 100 mg subcutaneously every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Uzedy (risperidone ER) 125 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "125 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 125 mg subcutaneously every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Uzedy (risperidone ER) 150 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "150 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 150 mg subcutaneously every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Uzedy (risperidone ER) 200 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "200 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 200 mg subcutaneously every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Uzedy (risperidone ER) 250 mg",
    drug: "Uzedy",
    generic: "risperidone extended-release",
    strength: "250 mg",
    form: "injection",
    route: "SubQ",
    quantity: "1 syringe",
    refills: "5",
    sig: "Inject 250 mg subcutaneously every 56 days (2 months)",
    schedule: "q2month",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Vivitrol (naltrexone ER) 380 mg",
    drug: "Vivitrol",
    generic: "naltrexone extended-release",
    strength: "380 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 380 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Alcohol use disorder",
  },
  {
    label: "Zyprexa Relprevv (olanzapine pamoate) 210 mg",
    drug: "Zyprexa Relprevv",
    generic: "olanzapine pamoate",
    strength: "210 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 210 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Zyprexa Relprevv (olanzapine pamoate) 300 mg",
    drug: "Zyprexa Relprevv",
    generic: "olanzapine pamoate",
    strength: "300 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 300 mg intramuscularly every 14 days (2 weeks)",
    schedule: "q2w",
    category: "Antipsychotic (atypical)",
  },
  {
    label: "Zyprexa Relprevv (olanzapine pamoate) 405 mg",
    drug: "Zyprexa Relprevv",
    generic: "olanzapine pamoate",
    strength: "405 mg",
    form: "injection",
    route: "IM",
    quantity: "1 vial",
    refills: "5",
    sig: "Inject 405 mg intramuscularly every 28 days (1 month)",
    schedule: "monthly",
    category: "Antipsychotic (atypical)",
  },
];

export const LAI_CATALOG: LaiCatalogEntry[] = [...RAW].sort((a, b) =>
  a.label.localeCompare(b.label, "en"),
);

// Sig dropdown options requested for the prescribe form. The catalog pre-fills
// a full sig string per medication; this list is for free-form selection on any
// LAI prescription (subcutaneous template by default — prescriber can edit IM
// or other route inline in the textarea after selecting an interval).
export const SIG_INTERVAL_OPTIONS: { value: string; label: string }[] = [
  { value: "Inject subcutaneously every 14 days (2 weeks)", label: "Every 14 days (2 weeks)" },
  { value: "Inject subcutaneously every 28 days (1 month)", label: "Every 28 days (1 month)" },
  { value: "Inject subcutaneously every 42 days (1.5 months)", label: "Every 42 days (1.5 months)" },
  { value: "Inject subcutaneously every 84 days (3 months)", label: "Every 84 days (3 months)" },
  { value: "Inject subcutaneously every 168 days (6 months)", label: "Every 168 days (6 months)" },
];
